name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures that the 'deploy' job only runs if the 'test' job completes successfully
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
          environment_id: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          service_id: ${{ secrets.RAILWAY_SERVICE_ID }}
          build_command: 'mvn clean package'
          start_command: 'java -jar target/international-currency-converter-0.0.1-SNAPSHOT.jar'
          dockerfile: Dockerfile
